"""Pre-defined research goals: each goal is a composable unit of research."""

GOALS = {
    "landscape": {
        "name": "Map Research Landscape",
        "description": "Complete end-to-end analysis of a research field including topic discovery, trend analysis, key authors, collaboration patterns, field evolution, and a full research report with publication-quality figures.",
        "icon": "Globe",
        "color": "#6366f1",
        "module_chain": [
            "acquisition", "topic_modeling",
            "trends", "sources", "geopolitical", "networks", "authors",
            "evolution", "bursts", "narrative",
            "growth_figure", "keyword_network_figure", "collaboration_figure",
            "thematic_evolution_figure", "landscape_figure",
            "report", "gather",
        ],
        "outputs": [
            "topic_clusters", "trend_analysis", "key_authors",
            "collaboration_map", "field_evolution", "figures", "report",
        ],
        "supports_refinement": True,
        "estimated_minutes": "15-30",
    },
    "topics": {
        "name": "Discover Research Topics",
        "description": "Identify and explore the main research topics in a field using AI-powered BERTopic clustering. Get a visual map of the research landscape.",
        "icon": "Layers",
        "color": "#10b981",
        "module_chain": ["acquisition", "topic_modeling", "landscape_figure"],
        "outputs": ["topic_clusters", "topic_landscape"],
        "supports_refinement": True,
        "estimated_minutes": "8-15",
    },
    "trends": {
        "name": "Analyze Publication Trends",
        "description": "Track publication growth over time, calculate Compound Annual Growth Rate (CAGR), and visualize the temporal evolution of research output.",
        "icon": "TrendingUp",
        "color": "#f59e0b",
        "module_chain": ["acquisition", "trends", "growth_figure"],
        "outputs": ["growth_timeline", "cagr_analysis"],
        "supports_refinement": False,
        "estimated_minutes": "5-10",
    },
    "experts": {
        "name": "Identify Key Researchers",
        "description": "Find the most prolific and cited authors, top journals and venues, and international collaboration patterns across countries.",
        "icon": "Users",
        "color": "#ec4899",
        "module_chain": ["acquisition", "authors", "sources", "geopolitical", "collaboration_figure"],
        "outputs": ["top_authors", "top_journals", "collaboration_map"],
        "supports_refinement": False,
        "estimated_minutes": "5-10",
    },
    "evolution": {
        "name": "Track Field Evolution",
        "description": "Analyze how research themes evolve over time, detect emerging and declining topics with burst detection, and visualize thematic shifts.",
        "icon": "GitBranch",
        "color": "#8b5cf6",
        "module_chain": ["acquisition", "topic_modeling", "evolution", "bursts", "thematic_evolution_figure"],
        "outputs": ["thematic_evolution", "burst_keywords", "evolution_figure"],
        "supports_refinement": True,
        "estimated_minutes": "10-20",
    },
    "quick-scan": {
        "name": "Quick Literature Scan",
        "description": "A fast overview of a research field: fetch papers from OpenAlex, get basic publication statistics, and explore top journals and keywords.",
        "icon": "Search",
        "color": "#06b6d4",
        "module_chain": ["acquisition"],
        "outputs": ["paper_count", "top_journals", "top_keywords"],
        "supports_refinement": False,
        "estimated_minutes": "3-8",
    },
}
